//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_TYPE_MASTER
    {
        public int CAT_TYPE_CODE { get; set; }
        public string CAT_TYPE_DESCRIPTION { get; set; }
        public int CREATE_BY { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public Nullable<int> UPDATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public byte IS_ACTIVE { get; set; }
    }
}
