//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORY
    {
        public CATEGORY()
        {
            this.PRODUCT_MASTER = new HashSet<PRODUCT_MASTER>();
            this.SUB_CATEGORY = new HashSet<SUB_CATEGORY>();
        }
    
        public int CAT_CODE { get; set; }
        public string CAT_NAM { get; set; }
        public int CREATE_BY { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public Nullable<int> UPDATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public byte IS_ACTIVE { get; set; }
    
        public virtual ICollection<PRODUCT_MASTER> PRODUCT_MASTER { get; set; }
        public virtual ICollection<SUB_CATEGORY> SUB_CATEGORY { get; set; }
    }
}
