//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER_PRODUCT_RATE_MASTER
    {
        public int CUST_PROD_RATE_ID { get; set; }
        public int P_CODE { get; set; }
        public Nullable<int> CUST_ID { get; set; }
        public Nullable<int> SGCODE { get; set; }
        public string CUST_SGCODE { get; set; }
        public string SALE_CALC_ON { get; set; }
        public Nullable<decimal> SALE_CALC_PER { get; set; }
        public Nullable<decimal> SALE_CALC_AMT { get; set; }
        public Nullable<decimal> DF_SAL_RATE { get; set; }
        public string CUST_P_CODE { get; set; }
        public Nullable<int> MAIN_QTY { get; set; }
        public Nullable<int> FREE_QTY { get; set; }
        public Nullable<int> FREE_PCODE { get; set; }
        public Nullable<decimal> CASH_DISC_PER { get; set; }
        public int NORMAL_LEAD_TIME { get; set; }
        public Nullable<int> MAX_LEAD_TIME { get; set; }
        public int BATCH_QTY { get; set; }
        public int MIN_ORDER_BATCH { get; set; }
        public string NARRATION { get; set; }
        public Nullable<int> TAX_CODE { get; set; }
        public Nullable<decimal> APMC_PER { get; set; }
        public Nullable<decimal> OCTROI_PER { get; set; }
        public Nullable<int> CONTAINOR_CHARGES { get; set; }
        public Nullable<int> HANDLING_FREIGHT_CHARGES { get; set; }
        public Nullable<int> OTHER_CHARGES { get; set; }
        public Nullable<System.DateTime> ST_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public int CREATE_BY { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<int> UPDATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public byte IS_ACTIVE { get; set; }
    
        public virtual CUSTOMER_MASTER CUSTOMER_MASTER { get; set; }
    }
}
