//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER_MASTER
    {
        public CUSTOMER_MASTER()
        {
            this.CUSTOMER_PRODUCT_RATE_MASTER = new HashSet<CUSTOMER_PRODUCT_RATE_MASTER>();
        }
    
        public int CUSTID { get; set; }
        public string CUST_NAME { get; set; }
        public string CUST_ADD1 { get; set; }
        public string CUST_ADD2 { get; set; }
        public string CUST_ADD3 { get; set; }
        public string CUST_ADD4 { get; set; }
        public string CONTACT_NOS { get; set; }
        public string CUST_EMAIL { get; set; }
        public Nullable<System.DateTime> BIRTH_DATE { get; set; }
        public Nullable<System.DateTime> JOIN_DATE { get; set; }
        public string CUST_TYPE { get; set; }
        public string REMARK { get; set; }
        public string LOGIN_NAME { get; set; }
        public string LOCALITY { get; set; }
        public string LANDMARK { get; set; }
        public int CREATE_BY { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CUST_GROUP { get; set; }
        public string BARCODE { get; set; }
        public Nullable<System.DateTime> ANNIV_DATE { get; set; }
        public Nullable<System.DateTime> DEACT_DATE { get; set; }
        public string DEACT_REASON { get; set; }
        public Nullable<System.DateTime> LAST_SALE_DATE { get; set; }
        public Nullable<int> MTD_NET_SALE { get; set; }
        public string CUST_TITLE { get; set; }
        public string GENDER { get; set; }
        public Nullable<int> MTH_AVG_SALE { get; set; }
        public Nullable<System.DateTime> MTH_CYCLE_ST_DATE { get; set; }
        public string INTRO_BY { get; set; }
        public string MOB_NO { get; set; }
        public string CUST_ADD5 { get; set; }
        public string CUST_ADD6 { get; set; }
        public string SUB_AREA { get; set; }
        public string CITY { get; set; }
        public Nullable<int> PIN_CODE { get; set; }
        public string STATE_CODE { get; set; }
        public string TEXT_ADDRESS { get; set; }
        public string SEND_OFFERS_VIA { get; set; }
        public string SEND_CONFIRM_VIA { get; set; }
        public Nullable<int> REF_CUSTID { get; set; }
        public string SOURCE_AWARNESS { get; set; }
        public string WEB_PASSWORD { get; set; }
        public string ALTERNATE_EMAIL { get; set; }
        public Nullable<int> CUST_SOCIETY { get; set; }
    
        public virtual ICollection<CUSTOMER_PRODUCT_RATE_MASTER> CUSTOMER_PRODUCT_RATE_MASTER { get; set; }
    }
}
