//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestWPF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FruitBytesEntities : DbContext
    {
        public FruitBytesEntities()
            : base("name=FruitBytesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BRAND> BRANDS { get; set; }
        public DbSet<CAT_TYPE_MASTER> CAT_TYPE_MASTER { get; set; }
        public DbSet<CATEGORY> CATEGORies { get; set; }
        public DbSet<CUSTOMER_MASTER> CUSTOMER_MASTER { get; set; }
        public DbSet<CUSTOMER_PRODUCT_RATE_MASTER> CUSTOMER_PRODUCT_RATE_MASTER { get; set; }
        public DbSet<LOGIN> LOGINs { get; set; }
        public DbSet<MANUFACT> MANUFACTs { get; set; }
        public DbSet<PAYMENT_MASTER> PAYMENT_MASTER { get; set; }
        public DbSet<POS_HEADER> POS_HEADER { get; set; }
        public DbSet<PRODUCT_MASTER> PRODUCT_MASTER { get; set; }
        public DbSet<PUR_DET> PUR_DET { get; set; }
        public DbSet<PUR_HDR> PUR_HDR { get; set; }
        public DbSet<STOCK_SUMMARY> STOCK_SUMMARY { get; set; }
        public DbSet<SUB_CATEGORY> SUB_CATEGORY { get; set; }
        public DbSet<SUPPLIER_MASTER> SUPPLIER_MASTER { get; set; }
        public DbSet<SUPPLIER_RATE_MASTER> SUPPLIER_RATE_MASTER { get; set; }
        public DbSet<POS_DETAIL> POS_DETAIL { get; set; }
        public DbSet<POS_PAYMENT> POS_PAYMENT { get; set; }
        public DbSet<STOCK_LEDGER> STOCK_LEDGER { get; set; }
    }
}
