//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGIN
    {
        public int USER_ID { get; set; }
        public string USER_NAME { get; set; }
        public string PASS { get; set; }
        public int CREATE_BY { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public int UPDATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<byte> IS_ACTIVE { get; set; }
    }
}
