//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENT_MASTER
    {
        public int PMT_TYPE { get; set; }
        public string PMT_NAME { get; set; }
        public int CREATE_BY { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public int UPDATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public byte IS_ACTIVE { get; set; }
        public string ON_MRP { get; set; }
        public string ALLOW_MULTIPLE { get; set; }
        public string PMT_GROUP { get; set; }
        public string ONLINE_PMT { get; set; }
        public Nullable<double> CHARGES_AMT { get; set; }
    }
}
