//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_DETAIL
    {
        public Nullable<int> V_NO { get; set; }
        public string DEP_CODE { get; set; }
        public int P_CODE { get; set; }
        public string BARCODE { get; set; }
        public Nullable<int> QTY { get; set; }
        public Nullable<double> RATE { get; set; }
        public Nullable<double> AMOUNT { get; set; }
        public string R_DOCTYPE { get; set; }
        public Nullable<int> R_LOTNO { get; set; }
        public int CREATE_BY { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public int UPDTEA_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<int> SRNO { get; set; }
        public Nullable<int> MRP { get; set; }
        public Nullable<int> SCHEME_DISC { get; set; }
        public Nullable<int> BILL_DISC { get; set; }
        public Nullable<int> ITEM_TOT_AMT { get; set; }
        public Nullable<int> TAX_AMOUNT { get; set; }
        public string TAX_CODE { get; set; }
        public string FREE_ITEM { get; set; }
        public Nullable<int> COST_RATE { get; set; }
        public string SCAN_INDICATOR { get; set; }
        public string SALESMAN_ID { get; set; }
        public string ACTION_IND { get; set; }
        public Nullable<int> DF_SALE_RATE { get; set; }
        public string CO_BATCH_NO { get; set; }
        public Nullable<System.DateTime> EXPIRY_DATE { get; set; }
        public byte IS_ACTIVE { get; set; }
    
        public virtual PRODUCT_MASTER PRODUCT_MASTER { get; set; }
    }
}
