//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_PAYMENT
    {
        public int POS_PAYMENT_ID { get; set; }
        public int V_NO { get; set; }
        public Nullable<int> PMT_TYPE { get; set; }
        public Nullable<int> PMT_CODE { get; set; }
        public Nullable<int> REFNO { get; set; }
        public Nullable<int> AMOUNT { get; set; }
        public string NARRATION { get; set; }
        public int CREATE_BY { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public int UPDATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string PMT_REF { get; set; }
        public Nullable<int> PMT_CHRG { get; set; }
    }
}
