//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_MASTER
    {
        public PRODUCT_MASTER()
        {
            this.POS_DETAIL = new HashSet<POS_DETAIL>();
            this.STOCK_LEDGER = new HashSet<STOCK_LEDGER>();
            this.STOCK_SUMMARY = new HashSet<STOCK_SUMMARY>();
            this.SUPPLIER_RATE_MASTER = new HashSet<SUPPLIER_RATE_MASTER>();
        }
    
        public int P_CODE { get; set; }
        public string P_NAME { get; set; }
        public string P_DESCRIPTION { get; set; }
        public string P_TYPE { get; set; }
        public Nullable<int> REF_P_CODE { get; set; }
        public int CAT_CODE { get; set; }
        public int SUB_CAT_CODE { get; set; }
        public string BARCODE { get; set; }
        public int BRAND_CODE { get; set; }
        public Nullable<int> CLASS_CODE { get; set; }
        public Nullable<int> PK_SIZE { get; set; }
        public string UNIT { get; set; }
        public string PK_FORM { get; set; }
        public string PRE_BAR_CODED { get; set; }
        public string TAXABLE { get; set; }
        public int QTY_PUR_PK { get; set; }
        public string PK_TYPE { get; set; }
        public int CREATE_BY { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public int UPDATE_BY { get; set; }
        public Nullable<int> UPDATE_DATE { get; set; }
        public byte IS_ACTIVE { get; set; }
        public int MANU_CODE { get; set; }
        public string P_IN_INV { get; set; }
        public string CAT_TYPE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public string EXPIRY_DATE_COMPULSORY { get; set; }
        public string INNER_PACK_SIZE { get; set; }
        public Nullable<System.DateTime> DEACT_DATE { get; set; }
        public string DEACT_REASON { get; set; }
        public string TOLERABLE_EXP_DATE_DM { get; set; }
        public Nullable<int> TOLERABLE_EXP_DATE_PERIOD { get; set; }
        public string CO_BATCH_NO_REQUIRED { get; set; }
        public string RATE_ENTERABLE { get; set; }
        public string CARTON_INFO_REQUIRED { get; set; }
        public string SUPPLY_TYPE { get; set; }
        public string MRP_BASED { get; set; }
        public Nullable<int> NET_CASE_WEIGHT { get; set; }
        public string MARKUP_IND { get; set; }
        public string MARKDOWN_IND { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
        public virtual MANUFACT MANUFACT { get; set; }
        public virtual ICollection<POS_DETAIL> POS_DETAIL { get; set; }
        public virtual PRODUCT_MASTER PRODUCT_MASTER1 { get; set; }
        public virtual PRODUCT_MASTER PRODUCT_MASTER2 { get; set; }
        public virtual SUB_CATEGORY SUB_CATEGORY { get; set; }
        public virtual ICollection<STOCK_LEDGER> STOCK_LEDGER { get; set; }
        public virtual ICollection<STOCK_SUMMARY> STOCK_SUMMARY { get; set; }
        public virtual ICollection<SUPPLIER_RATE_MASTER> SUPPLIER_RATE_MASTER { get; set; }
    }
}
