//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUR_HDR
    {
        public int V_NO { get; set; }
        public int SUPP_CODE { get; set; }
        public System.DateTime V_DATE { get; set; }
        public decimal GROSS_AMT { get; set; }
        public Nullable<decimal> DISCOUNT { get; set; }
        public Nullable<decimal> ST_AMT { get; set; }
        public Nullable<decimal> OCTROI_AMT { get; set; }
        public Nullable<decimal> TOT_AMT { get; set; }
        public Nullable<decimal> SC_AMT { get; set; }
        public Nullable<decimal> APMC_AMT { get; set; }
        public Nullable<decimal> ROUND_AMT { get; set; }
        public Nullable<decimal> CONT_AMT { get; set; }
        public decimal PUR_AMT { get; set; }
        public decimal SALE_AMT { get; set; }
        public Nullable<int> CR_DAYS { get; set; }
        public string BILLNO { get; set; }
        public Nullable<System.DateTime> BILL_DATE { get; set; }
        public string DC_NO { get; set; }
        public Nullable<System.DateTime> DC_DATE { get; set; }
        public string PO_NO { get; set; }
        public Nullable<System.DateTime> PO_DATE { get; set; }
        public string AUTH_FLG { get; set; }
        public string AUTH_UCODE { get; set; }
        public Nullable<System.DateTime> AUTH_DATE { get; set; }
        public int CREATE_BY { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public int UPDATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public byte IS_ACTIVE { get; set; }
        public string NARRATION { get; set; }
        public Nullable<decimal> SPL_DISCOUNT { get; set; }
        public Nullable<decimal> OTH_DISCOUNT { get; set; }
        public Nullable<decimal> DISC_RETAINED { get; set; }
        public Nullable<decimal> DISC_PASSED { get; set; }
        public Nullable<decimal> HANDLING_FREIGHT_AMT { get; set; }
        public Nullable<decimal> OTHER_AMT { get; set; }
        public string CONSIGNMENT { get; set; }
        public Nullable<decimal> PUR_RET_AMT { get; set; }
        public Nullable<decimal> NET_PAYABLE_AMT { get; set; }
        public string UPD_UCODE { get; set; }
        public Nullable<System.DateTime> UPD_TDATE { get; set; }
        public string TAX_INVOICE { get; set; }
        public string FORM_TYPE { get; set; }
    }
}
