//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUR_DET
    {
        public int LOTNO { get; set; }
        public Nullable<int> P_CODE { get; set; }
        public int NO_OF_PKS { get; set; }
        public int QTY_PUR_PK { get; set; }
        public int BILL_QTY { get; set; }
        public int R_QTY { get; set; }
        public int BILL_RATE { get; set; }
        public decimal BILL_GROSS_AMT { get; set; }
        public decimal R_GROSS_AMT { get; set; }
        public Nullable<decimal> P_DISCOUNT { get; set; }
        public int TAX_CODE { get; set; }
        public decimal TAX_AMT { get; set; }
        public Nullable<decimal> ADJ_AMT { get; set; }
        public Nullable<int> PUR_AMT { get; set; }
        public Nullable<int> PUR_CODE { get; set; }
        public Nullable<int> LANDING_COST { get; set; }
        public int MRP { get; set; }
        public Nullable<int> SELLING_RATE { get; set; }
        public string PK_TYPE { get; set; }
        public Nullable<decimal> PK_AMT { get; set; }
        public Nullable<decimal> PK_TYPE_NOS { get; set; }
        public Nullable<System.DateTime> EXPIRY_DATE { get; set; }
        public string NARRATION { get; set; }
        public string CO_BATCH_NO { get; set; }
        public string BARCODE { get; set; }
        public Nullable<decimal> SPL_DISCOUNT { get; set; }
        public Nullable<decimal> OTH_DISCOUNT { get; set; }
        public Nullable<decimal> DISC_RETAINED { get; set; }
        public Nullable<decimal> DISC_PASSED { get; set; }
        public Nullable<decimal> ST_AMT { get; set; }
        public Nullable<decimal> SC_AMT { get; set; }
        public Nullable<decimal> TOT_AMT { get; set; }
        public Nullable<decimal> OCTROI_AMT { get; set; }
        public Nullable<decimal> APMC_AMT { get; set; }
        public Nullable<decimal> CONT_AMT { get; set; }
        public Nullable<decimal> HANDLING_FREIGHT_AMT { get; set; }
        public Nullable<decimal> OTHER_AMT { get; set; }
        public Nullable<decimal> FREE_PCODE { get; set; }
        public Nullable<int> FREE_QTY { get; set; }
        public Nullable<int> SRNO { get; set; }
        public Nullable<int> V_NO { get; set; }
        public string SCHEME_NARRATION { get; set; }
        public Nullable<int> SALE_TYPE { get; set; }
        public string DEP_CODE { get; set; }
        public Nullable<int> SUPP_LAMT { get; set; }
        public string CARTON_CODE { get; set; }
        public Nullable<int> ALLOC_QTY { get; set; }
        public int CREATE_BY { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public int UPDATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<byte> IS_ACTIVE { get; set; }
    }
}
