//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK_LEDGER
    {
        public string BR_CODE { get; set; }
        public string DEP_CODE { get; set; }
        public string DOC_TYPE { get; set; }
        public int DOCNO { get; set; }
        public int P_CODE { get; set; }
        public string RI { get; set; }
        public System.DateTime V_DATE { get; set; }
        public int R_LOTNO { get; set; }
        public int INV_QTY { get; set; }
        public int RATE { get; set; }
        public int AMOUNT { get; set; }
        public int REFNO { get; set; }
        public Nullable<int> PARTY_CODE { get; set; }
        public string OT_BR_CODE { get; set; }
        public string OT_DEP_CODE { get; set; }
        public int SALE_RATE { get; set; }
        public string TRF_RET_DAMAGE { get; set; }
        public string CO_BATCH_NO { get; set; }
        public Nullable<int> MRP { get; set; }
        public Nullable<int> TAX_CODE { get; set; }
        public Nullable<int> TAX_AMT { get; set; }
        public Nullable<int> DROP_SHIP { get; set; }
        public Nullable<int> DF_SALE_RATE { get; set; }
        public Nullable<int> COGS_VAT_AMT { get; set; }
        public Nullable<int> NET_SALE_VALUE { get; set; }
        public Nullable<int> SUPP_CODE { get; set; }
        public Nullable<System.DateTime> T_DATE { get; set; }
        public Nullable<int> CASE_WEIGHT { get; set; }
        public int CREATE_BY { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public int UPDATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public byte IS_ACTIVE { get; set; }
    
        public virtual PRODUCT_MASTER PRODUCT_MASTER { get; set; }
    }
}
