//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUB_CATEGORY
    {
        public SUB_CATEGORY()
        {
            this.PRODUCT_MASTER = new HashSet<PRODUCT_MASTER>();
        }
    
        public int SUB_CAT_CODE { get; set; }
        public string SUB_CAT_NAME { get; set; }
        public int CAT_COD { get; set; }
        public int CREATE_BY { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public int UPDATE_BY { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public byte IS_ACTIVE { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
        public virtual ICollection<PRODUCT_MASTER> PRODUCT_MASTER { get; set; }
    }
}
