//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUPPLIER_MASTER
    {
        public int SUPP_CODE { get; set; }
        public string SUPP_NAME { get; set; }
        public int CREATE_BY { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public int UPDATE_BY { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public byte IS_ACTIVE { get; set; }
        public string CHEQUE_NAME { get; set; }
        public Nullable<int> ORDER_BY { get; set; }
        public string ADDRESS { get; set; }
        public string CITY { get; set; }
        public string STATE_CODE { get; set; }
        public string COUNTRY_CODE { get; set; }
        public string PIN { get; set; }
        public string TEL1 { get; set; }
        public string TEL2 { get; set; }
        public string FAX { get; set; }
        public string CPERSON { get; set; }
        public string TYPE { get; set; }
        public Nullable<int> CRDAYS { get; set; }
        public Nullable<int> CRLIMIT { get; set; }
        public string GST_NO { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
    }
}
